FROM docker.io/library/archlinux:base

COPY libnexpod-setup /setup/
RUN bash /setup/libnexpod-setup
# don't delete the script so users have an easier time at looking at what's done by it

LABEL com.github.libnexpod="true" \
    usage="This is meant to be used by the libnexpod library and tools based on it." \
    summary="Base Image for Creating Arch Linux libnexpod Containers" \
    maintainer="Kilian Hanich <khanich.opensource@gmx.de>"
