name: "CI with One Image"

inputs:
  image_name:
    description: "name of the to be used image"
    required: true
  image_tag:
    description: "tag of the to be used image"
    required: true

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - uses: redhat-actions/buildah-build@v2
    name: "build image"
    with:
      image: "libnexpod-test-${{ inputs.image_name }}"
      tags: ${{ inputs.image_tag }}
      containerfiles: "images/${{ inputs.image_name }}/Containerfile"
  - uses: mlugg/setup-zig@v1
    with:
      version: 0.13.0
  - name: "Debug"
    run: |
    zig build
    zig build test
  - name: "Release"
    run: |
    zig build --release
    zig build test --release
